### ISSUE TITLE
Add representation for constant expression

### ISSUE THREAD

**Issue by ahuoguo** [thesuhas/orca#13]
I'm trying to add the ability to add globals in orca

However, it is pretty hard to create our own `Global` type since it relies on `InitExpr` defined in [wasmparser](https://docs.rs/wasmparser/latest/wasmparser/struct.ConstExpr.html), which is hard to manipulate

We can do something like walrus https://docs.rs/walrus/latest/src/walrus/const_expr.rs.html#13-22

**Comment by thesuhas** [comment]
Similarly, we will need to do something for functions as well. But this will be more complicated, will have to modify two fields:
1. `Funcs`: this is a mapping of function to types. We'll also need to a new type if this function signature is different from existing ones.
2. `Code Sections`: This contains the actual body of the functions and the instructions.
