### ISSUE TITLE
Alias should come after core instance

### ISSUE THREAD

**Issue by ahuoguo** [thesuhas/orca#20]
In the discussion in #9 

The ordering between 
`(core instance (;0;) (instantiate 0))` and `(alias core export 0 "memory" (core memory (;0;)))` does matter. It results in the output not passing `wasm-tools validate`, giving me the following error
```
error: unknown core instance 0: instance index out of bounds (at offset 0x71)
```

We need find the right way to encode alias

**Comment by thesuhas** [comment]
Can we raise an issue on `wasm-tools`?

**Comment by ahuoguo** [comment]
If this is a wasm-tools issue then yes (?)

**Comment by thesuhas** [comment]
Okay maybe not an issue but a discussion? We're doing everything similar to the docs and how dfinity is doing it. Talking to people on `wasm-tools` might give us a clear idea of what's happening and why

**Comment by ahuoguo** [comment]
Sounds good

**Comment by thesuhas** [comment]
https://github.com/bytecodealliance/wasm-tools/discussions/1658
