### ISSUE TITLE
Names not applying

### ISSUE THREAD

**Issue by guybedford** [thesuhas/orca#216]
I just tried the latest 0.1.4 and it seems the `"name"` section isn't being transformed properly.

I think the simplest approach here to test this is by running `wasm-tools print out.wasm -o out.wat` and checking that the functions still have their correct names in that output. For the transformations we are doing in ComponentizeJS this is unfortunately still not the case.

**Comment by thesuhas** [comment]
Hi,
Can you provide me with a sample input and output `.wasm`, and the command you're running ComponentizeJS with so that I can hunt down the issue?

**Comment by guybedford** [comment]
Looking into this further the issue might be in wasm-opt itself since the build output for StarlingMonkey under RelWithDebInfo isn't printing names either. Will reopen if I find the root of that, but for now moving to - https://github.com/bytecodealliance/StarlingMonkey/issues/173 for now.
