### ISSUE TITLE
Iteration of functions

### ISSUE THREAD

**Issue by vados-cosmonic** [thesuhas/orca#219]
Hey @thesuhas thanks for making this awesome project!

Was wondering if there was a reason that the `Iter` implementation on `Functions<'a>` was private to the crate? If there wasn't a reason other than minimalism/avoiding unnecessary exports, I'd certainly like to be able to iterate over the functions in a given module, instead of having to look up the functions (and their IDs) some other way.

Happy to contribute the tiny PR to make this happen

**Comment by thesuhas** [comment]
Hey!

I don't think there was a specific reason, feel free to make a PR! 

Note: The current implementation may also iterate over deleted functions (if functions in the original `.wasm` are deleted).

**Comment by thesuhas** [comment]
Thanks for the PR, I've merged it!

I'll make a new release in a day or so, I have another branch almost ready to be released. Hope that's okay!

**Comment by vados-cosmonic** [comment]
That sounds great! Thanks for the quick review :bow:

**Comment by thesuhas** [comment]
I've just released it!

**Comment by vados-cosmonic** [comment]
Thanks @thesuhas !
