### ISSUE TITLE
Injection API Design

### ISSUE THREAD

**Issue by thesuhas** [thesuhas/orca#33]
API is going to be something like this:
```rust
curr_instr.before().i32(0).if().end()
```

Wasmparser doc for instructions: https://docs.rs/wasmparser/0.212.0/wasmparser/enum.Operator.html
WASM instructions: https://webassembly.github.io/spec/core/binary/instructions.html

Instructions that will be needed:

- [x] i32
- [x] i64
- [x] f32
- [x] f64
- [x] i32 comparison
- [x] i64 comparison
- [x] f32 comparison
- [x] f64 comparison
- [x] LocalGet
- [x] LocalSet
- [x] i32Add
- [x] if
- [x] else
- [x] end
- [x] block
- [x] br
- [x] brif
- [x] call
- [x] loop
- [x] return
- [x] drop
- [ ] callref
- [x] unreachable
- [x] nop
- [x] memory instructions

**Comment by ejrgilbert** [comment]
This could also be a helpful model to refer to (no need to design completely from scratch):
https://docs.rs/walrus/latest/walrus/struct.InstrSeqBuilder.html

**Comment by thesuhas** [comment]
Floating point PR: https://github.com/bytecodealliance/wasm-tools/pull/1662

**Comment by thesuhas** [comment]
Floating point support now available via `warm-tools` 0.213.0
