### ISSUE TITLE
Create Test Suite to validate Round Trip

### ISSUE THREAD

**Issue by thesuhas** [thesuhas/orca#4]
Create a test suite to validate round trip for components. 
This already exists for modules, an example is dfinity's implementation [here](https://github.com/dfinity/ic/tree/master/rs/wasm_transform/tests). A simple way to generate a test suite is convert all of these to components but that may not cover any edge cases or nuances that are specific to components.

Another idea is to use `spin` microservices but those are too big and tough to debug.

Also look into [wasm spec tests](https://github.com/WebAssembly/spec/tree/main/test/core) and the wasm benchmarking platform [wish you were fast](https://github.com/composablesys/wish-you-were-fast) for ideas on how to generate test cases.

**Comment by thesuhas** [comment]
There seems to be a test suite for the component model coming at some point: https://github.com/WebAssembly/component-model

**Comment by ahuoguo** [comment]
We currently cant create a roundtrip for the spin test case https://www.diffchecker.com/pXS27KAs/

#25
